# Note: It requires docker-compose 1.6.0+
#
# Usage: docker-compose up -d
version: '3'

services:
  android-container:
    image: budtmo/docker-android:emulator_13.0
    ports:
      - "6080:6080"
      - "4723:4723"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - APPIUM=true
      - EMULATOR_ARGS=-memory 8192 -partition-size 8096
    devices:
      - /dev/kvm
    container_name: android-container
    restart: always